caught exception. exception what: max recursion deepness reached!
